steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/mi7rab/mi7rab/afya:$SHORT_SHA
      - -t
      - us-central1-docker.pkg.dev/mi7rab/mi7rab/afya:latest
      - .

  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - --all-tags
      - us-central1-docker.pkg.dev/mi7rab/mi7rab/afya

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - afya
      - --image=us-central1-docker.pkg.dev/mi7rab/mi7rab/afya:$SHORT_SHA
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --memory=512Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=3
      - --add-cloudsql-instances=mi7rab:us-central1:mi7rab-db
      - --service-account=mi7rab-run@mi7rab.iam.gserviceaccount.com
      - --set-env-vars=NODE_ENV=production,BETTER_AUTH_URL=https://afya-qjyft4sfwa-uc.a.run.app,CORS_ORIGINS=*
      - >-
        --set-secrets=DATABASE_URL=afya-database-url:latest,AUTH_DATABASE_URL=database-url:latest,BETTER_AUTH_SECRET=better-auth-secret:latest

images:
  - us-central1-docker.pkg.dev/mi7rab/mi7rab/afya:$SHORT_SHA
  - us-central1-docker.pkg.dev/mi7rab/mi7rab/afya:latest

options:
  logging: CLOUD_LOGGING_ONLY
